server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

redisson:
  url: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
  database: ${spring.data.redis.database}